load("ext://helm_resource", "helm_repo", "helm_resource")
load("ext://uibutton", "cmd_button")
load("../devcore/Tiltfile", "tilt_port")

extension_root = os.getcwd()


def localstack_up(add_buttons = True):
    """Deploy Localstack using Helm Chart."""

    # Pre-create persistent volume claim so Tilt doesn't destroy data.
    k8s_yaml(os.path.join(extension_root, "k8s/pvc-localstack.yaml"))
    k8s_resource(
        new_name = "localstack-storage",
        objects = ["localstack:persistentvolumeclaim"],
        labels = "localstack",
        trigger_mode=TRIGGER_MODE_AUTO,
    )

    # Install Localstack from Helm with Tilt-friendly values.yaml.
    helm_repo(
        "localstack-repo",
        "https://helm.localstack.cloud",
        labels = "localstack",
        trigger_mode=TRIGGER_MODE_AUTO,
    )
    helm_resource(
        "localstack",
        "localstack-repo/localstack",
        resource_deps = [
            "localstack-repo",
            "localstack-storage"
        ],
        flags = [
            "--values",
            os.path.join(extension_root, "helm/values.yaml"),
        ],
        labels = "localstack",
    )

    if add_buttons:
        add_ui_buttons()


def add_ui_buttons():
    """Add UI Buttons to toggle Localstack and reset data."""
    port = tilt_port()

    reset_script = os.path.join(extension_root, "scripts/reset.sh")
    cmd_button(
        "localstack:reset",
        argv = ["sh", reset_script, port],
        resource="localstack",
        icon_name = "restart_alt",
        text = "Reset Localstack",
        requires_confirmation = True,
    )

    toggle_script = os.path.join(extension_root, "scripts/toggle.sh")
    icon = "cloud" if "localstack" in sys.argv or not sys.argv[2:] else "cloud_off"
    cmd_button(
        "localstack:toggle",
        argv = ["sh", toggle_script, port],
        location = "nav",
        icon_name = icon,
        text = "Toggle Localstack",
    )
