# Reference:
# https://github.com/localstack/helm-charts/blob/main/charts/localstack/values.yaml

image:
  tag: "2.2.0"

service:
  type: ClusterIP
  annotations: {}
  ipFamilies: []
  ipFamilyPolicy: ""
  externalTrafficPolicy: ""
  edgeService:
    name: edge
    targetPort: 4566
    nodePort:
  externalServicePorts:
    start: 4510
    end: 4560

persistence:
  enabled: true
  # Using an existing PVC so we can annotate it
  existingClaim: localstack
