"""Some sensible defaults and tools to provide a more consistent experience across clusters."""

load_dynamic("Tiltfile.d/docker_prune.star")
symbols = load_dynamic("Tiltfile.d/local_dev_yaml.star")
local_dev = symbols["local_dev"]

load("Tiltfile.d/cluster_discovery.star", "context")
load("Tiltfile.d/storage_class.star", "setup_storage_class")
load("Tiltfile.d/ingress.star", "setup_ingress")

setup_storage_class(context)
setup_ingress(context)
