apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    tilt.dev/down-policy: keep
  labels:
    app.kubernetes.io/name: localstack
  name: localstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
