load("helm/Tiltfile", "load_helmchart")
load("minikube/Tiltfile", "load_minikube")


def ingress_nginx(resource_deps = [], labels = []):
    if k8s_context() == "minikube":
        load_minikube(resource_deps, labels)
    else:
        load_helmchart(resource_deps, labels)
