load("ext://uibutton", "cmd_button", "location")

script_path = os.path.join(os.getcwd(), "compile-requirements.sh")

def pip_compile_button(
    resource,
    requirements,
    destination="./",
    exec_path=None,
    compile_args=None,
):
    if not exec_path:
        exec_path = "deploy/%s" % resource

    if type(requirements) == type(list()):
        requirements= " ".join(requirements)

    cmd = [shlex.quote(script_path), exec_path, destination, requirements]
    if type(compile_args) == type(list()):
        cmd+=compile_args

    cmd_string = " ".join(cmd)

    cmd_button(
        "pip-compile",
        resource,
        argv=[
            "/bin/bash",
            "-c",
            cmd_string,
        ],
        location=location.RESOURCE,
        icon_name="build_circle",
    )
