load("ext://uibutton", "cmd_button", "location")

script_path = os.path.join(os.getcwd(), "compile-requirements.sh")

def pip_compile_button(
        resource,
        requirements,
        dev_requirements=None,
        exec_path=None,
):
    if not dev_requirements:
        dev_requirements = ""

    if not exec_path:
        exec_path = "deploy/%s" % resource

    cmd_button(
        "pip-compile",
        resource,
        argv=[
            "/bin/bash",
            "-c",
            f"{script_path} {exec_path} {requirements} {dev_requirements}",
        ],
        location=location.RESOURCE,
        icon_name="build_circle",
    )
